---
title: "hw01_gapminder"
author: "Gb"
date: '2017-09-14'
output: 
 md_document:
 variant: markdown_github
---
```{r}
library(tidyverse)
```
```{r}
library(gapminder)
```

```{r}
gapminder
```
```{r}
head(gapminder)
```
```{r}
tail(gapminder)
```
```{r}
str(gapminder)
```
```{r}
summary(gapminder)
```
```{r}
glimpse(gapminder)
```
```{r}
names(gapminder)
```
```{r}
plot(lifeExp ~ year, gapminder)
```
```{r}
plot(lifeExp ~ gdpPercap, gapminder)
```
```{r}
head(gapminder$lifeExp)
```
```{r}
summary(gapminder$lifeExp)
```
```{r}
hist(gapminder$lifeExp)
```
```{r}
summary(gapminder$year)
```
```{r}
table(gapminder$year)
```
```{r}
class(gapminder$continent)
```
```{r}
summary(gapminder$continent)
```
```{r}
levels(gapminder$continent)
```
```{r}
nlevels(gapminder$continent)
```
```{r}
str(gapminder$continent)
```
```{r}
table(gapminder$continent)
```
```{r}
barplot(table(gapminder$continent))
```
```{r}
p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp))
p <- p + scale_x_log10() 
p + geom_point() 
p + geom_point(aes(color = continent)) 
p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 3, se = FALSE)
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
```

update







